---
title: CS0156 chyby kompilátoru
ms.date: 07/20/2015
f1_keywords:
- CS0156
helpviewer_keywords:
- CS0156
ms.assetid: 32026b1b-bcd7-4464-b63f-3b38c00452a6
ms.openlocfilehash: f310b4b2b8aa320146d9114a999a82dcae2bb528
ms.sourcegitcommit: 3d5d33f384eeba41b2dff79d096f47ccc8d8f03d
ms.translationtype: MT
ms.contentlocale: cs-CZ
ms.lasthandoff: 05/04/2018
ms.locfileid: "33280933"
---
# <a name="compiler-error-cs0156"></a><span data-ttu-id="0d1b1-102">CS0156 chyby kompilátoru</span><span class="sxs-lookup"><span data-stu-id="0d1b1-102">Compiler Error CS0156</span></span>
<span data-ttu-id="0d1b1-103">Příkaz throw bez argumentů není povolen v a nakonec klauzuli, která je vnořit nejbližší obklopuje catch – klauzule</span><span class="sxs-lookup"><span data-stu-id="0d1b1-103">A throw statement with no arguments is not allowed in a finally clause that is nested inside the nearest enclosing catch clause</span></span>  
  
 <span data-ttu-id="0d1b1-104">A [throw](../../csharp/language-reference/keywords/throw.md) příkaz bez parametrů se může vyskytovat pouze v **catch** klauzule, které nepřijímá žádné parametry.</span><span class="sxs-lookup"><span data-stu-id="0d1b1-104">A [throw](../../csharp/language-reference/keywords/throw.md) statement with no parameters can only appear in a **catch** clause that takes no parameters.</span></span>  
  
 <span data-ttu-id="0d1b1-105">Další informace najdete v tématu [příkazy zpracování výjimek](../../csharp/language-reference/keywords/exception-handling-statements.md) a [výjimky a zpracování výjimek](../../csharp/programming-guide/exceptions/index.md).</span><span class="sxs-lookup"><span data-stu-id="0d1b1-105">For more information, see [Exception Handling Statements](../../csharp/language-reference/keywords/exception-handling-statements.md) and [Exceptions and Exception Handling](../../csharp/programming-guide/exceptions/index.md).</span></span>  
  
 <span data-ttu-id="0d1b1-106">Následující ukázka generuje CS0156:</span><span class="sxs-lookup"><span data-stu-id="0d1b1-106">The following sample generates CS0156:</span></span>  
  
```csharp  
// CS0156.cs  
using System;  
  
namespace MyNamespace  
{  
   public class MyClass2 : Exception  
   {  
   }  
  
   public class MyClass  
   {  
      public static void Main()  
      {  
         try  
         {  
            throw;   // CS0156  
         }  
  
         catch(MyClass2)  
         {  
            throw;   // this throw is valid  
         }  
      }  
   }  
}  
```
