---
title: "& č. 39; Catch & č. 39; nelze vložit po & č. 39; Nakonec & č. 39; v rámci a & č. 39; Zkuste & č. 39; příkaz"
ms.date: 07/20/2015
ms.prod: .net
ms.technology: devlang-visual-basic
ms.topic: article
f1_keywords:
- vbc30379
- bc30379
helpviewer_keywords: BC30379
ms.assetid: 33d1278b-cf10-4c66-aaf8-08a4372f370b
caps.latest.revision: "8"
author: dotnet-bot
ms.author: dotnetcontent
ms.openlocfilehash: b9638f930b411599ec1a9685409ff2430221f31f
ms.sourcegitcommit: 4f3fef493080a43e70e951223894768d36ce430a
ms.translationtype: MT
ms.contentlocale: cs-CZ
ms.lasthandoff: 11/21/2017
---
# <a name="39catch39-cannot-appear-after-39finally39-within-a-39try39-statement"></a>& č. 39; Catch & č. 39; nelze vložit po & č. 39; Nakonec & č. 39; v rámci a & č. 39; Zkuste & č. 39; příkaz
A `Catch` příkazu se zobrazí v kódu po `Finally` ukončení `Try` příkaz bloku. `Catch`musí být v rámci `Try...Catch...Finally` příkaz bloku.  
  
 **ID chyby:** BC30379  
  
## <a name="to-correct-this-error"></a>Oprava této chyby  
  
1.  Přesunout `Catch` příkaz na vhodnější místo v kódu.  
  
## <a name="see-also"></a>Viz také  
 [Try... Catch... Finally – příkaz](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)  
 [Přehled strukturovaného zpracování výjimek v jazyce Visual Basic](http://msdn.microsoft.com/en-us/bb81af80-a735-4873-9711-6151a48e418a)
