---
title: Chyba kompilátoru CS0103
ms.date: 07/20/2015
f1_keywords:
- CS0103
helpviewer_keywords:
- CS0103
ms.assetid: fd1f2104-a945-4dba-8137-8ef869826062
ms.openlocfilehash: 7bf3e71d9616baca5efb86983e82450fc1d01d88
ms.sourcegitcommit: 3d5d33f384eeba41b2dff79d096f47ccc8d8f03d
ms.translationtype: MT
ms.contentlocale: cs-CZ
ms.lasthandoff: 05/04/2018
---
# <a name="compiler-error-cs0103"></a>Chyba kompilátoru CS0103
Název identifikátoru v aktuálním kontextu neexistuje.  
  
 Došlo pokusu o použijte název, který neexistuje ve třídě, [obor názvů](../../../csharp/language-reference/keywords/namespace.md), nebo oboru. Zkontrolujte, zda název a zkontrolujte vaše pomocí direktivy a odkazy na sestavení, abyste měli jistotu, že název, který se pokoušíte použít je k dispozici.  
  
 Této chybě dochází často deklarovat proměnnou ve smyčce nebo `try` nebo `if` blokovat a pak se pokusíte k němu přístup z nadřazených či samostatné bloku, jak je znázorněno v následujícím příkladu.  
  
```csharp  
using System;  
  
class MyClass1  
{  
    public static void Main()  
    {  
        try  
        {  
            // The following declaration is only available inside the try block.  
            MyClass1 conn = new MyClass1();  
        }  
        catch (Exception e)  
        {  
            // The following expression causes error CS0103, because variable  
            // conn only exists in the try block.  
            if (conn != null)   
                Console.WriteLine("{0}", e);  
        }  
    }  
}  
```  
  
 Následující příklad vyřeší chyby.  
  
```csharp  
using System;  
  
class MyClass2  
{  
    public static void Main()  
    {  
        // To resolve the error in the example, the first step is to   
        // move the declaration of conn out of the try block. The following  
        // declaration is available throughout the Main method.  
        MyClass2 conn = null;  
        try  
        {  
            // Inside the try block, use the conn variable that you declared  
            // previously.  
            conn = new MyClass2();  
        }  
        catch (Exception e)  
        {  
            // The following expression no longer causes an error, because  
            // the declaration of conn is in scope.  
            if (conn != null)   
                Console.WriteLine("{0}", e);  
        }  
    }  
}  
```
