---
title: "Upozornění kompilátoru (úroveň 1) CS1058"
ms.date: 07/20/2015
ms.prod: .net
ms.technology:
- devlang-csharp
ms.topic: error-reference
f1_keywords:
- CS1058
helpviewer_keywords:
- CS1058
ms.assetid: ed50590c-f130-47c3-976d-322a6c8f996d
caps.latest.revision: 
author: BillWagner
ms.author: wiwagn
ms.openlocfilehash: 3d5d32b17c9803c4df82ff4e8cc3b0672a386b78
ms.sourcegitcommit: bd1ef61f4bb794b25383d3d72e71041a5ced172e
ms.translationtype: MT
ms.contentlocale: cs-CZ
ms.lasthandoff: 10/18/2017
---
# <a name="compiler-warning-level-1-cs1058"></a>Upozornění kompilátoru (úroveň 1) CS1058
Předchozí klauzule catch již zachytí všechny výjimky. Všechny výjimky vydané bude zabaleny v System.Runtime.CompilerServices.RuntimeWrappedException  
  
 Tento atribut zapříčiní CS1058 pokud `catch()` bloku nemá žádný typ po zadané výjimky `catch (System.Exception e)` bloku. Upozornění informuje o tom, který `catch()` bloku nezachytí žádné výjimky.  
  
 A `catch()` blokovat po `catch (System.Exception e)` bloku může zachytit výjimky specifikací CLS, pokud `RuntimeCompatibilityAttribute` je nastaven na hodnotu false v souboru AssemblyInfo.cs: `[assembly: RuntimeCompatibilityAttribute(WrapNonExceptionThrows = false)]`. Pokud tento atribut není explicitně nastavena na hodnotu false, jsou všechny výjimky vyvolané bez podpory CLS zabaleny jako výjimky a `catch (System.Exception e)` je zachytí bloku. Další informace najdete v tématu [postupy: zachycení bez výjimek specifikací CLS -](../../../csharp/programming-guide/exceptions/how-to-catch-a-non-cls-exception.md).  
  
## <a name="example"></a>Příklad  
 Následující příklad generuje CS1058.  
  
```csharp  
// CS1058.cs  
// CS1058 expected  
using System.Runtime.CompilerServices;  
  
// the following attribute is set to true by default in the C# compiler  
// set to false in your source code to resolve CS1058  
[assembly: RuntimeCompatibilityAttribute(WrapNonExceptionThrows = true)]  
  
class TestClass   
{  
   static void Main()   
   {  
      try {}  
  
      catch (System.Exception e) {   
         System. Console.WriteLine("Caught exception {0}", e);  
      }  
  
      catch {}   // CS1058. This line will never be reached.  
   }  
}  
```
